// using-rich-text-react-renderer/pages/products/[slug].js
import React from 'react';
import { GraphQLClient } from 'graphql-request';
import { RichText } from '@graphcms/rich-text-react-renderer';

const graphcms = new GraphQLClient(
  'https://api-eu-central-1.graphcms.com/v2/ck8sn5tnf01gc01z89dbc7s0o/master'
);

export async function getStaticProps({ params }) {
  const { product } = await graphcms.request(
    `
    query ProductPageQuery($slug: String!) {
      product(where: { slug: $slug }) {
        name
        content {
          raw
        }
      }
    }
  `,
    {
      slug: params.slug,
    }
  );

  return {
    props: {
      product,
    },
  };
}

export async function getStaticPaths() {
  const { products } = await graphcms.request(`
    {
      products {
        slug
      }
    }
  `);

  return {
    paths: products.map(({ slug }) => ({
      params: { slug },
    })),
    fallback: false,
  };
}

const ProductPage = ({ product }) => (
  <React.Fragment>
    <h1>{product.name}</h1>

    <RichText content={product.content.raw.children} />
  </React.Fragment>
);

export default ProductPage;

// with-sveltekit-and-graphql-request/src/routes/product/[slug].svelte
<script context="module">
  import { GraphQLClient } from 'graphql-request';
  export async function load(ctx) {
    const graphcms = new GraphQLClient(
      'https://api-eu-central-1.graphcms.com/v2/ck8sn5tnf01gc01z89dbc7s0o/master',
      {
        headers: {},
      }
    )
    const { product } = await graphcms.request(
      `query ProductPageQuery($slug: String!) { 
        product(where: { slug: $slug }) {
          name
          description
          price
        }
      }`,
      {
        slug: ctx.page.params.slug,
      }
    )
    return {
      props: {
        product,
      },
    }
  }
</script>

<script>
  export let product
</script>

<svelte:head>
  <title>{product.name}</title>
</svelte:head>

<h1>{product.name}</h1>
<p>{product.description}</p>
<p>${product.price / 100}</p>
