// current/react-apollo-blog/src/components/About.js
import React from 'react'
import gql from 'graphql-tag'
import { graphql } from 'react-apollo'

const About = ({ data: { loading, error, authors } }) => {
  if (error) return <h1>Error fetching authors!</h1>
  if (!loading) {
    return (
      <div>
        {authors.map(author => (
          <div className='About-author' key={author.id}>
            <div className='About-infoHeader'>
              <img
                className='About-img'
                alt={author.name}
                src={`https://media.graphcms.com/resize=w:100,h:100,fit:crop/${author.avatar.handle}`}
              />
              <h1>Hello! My name is {author.name}</h1>
            </div>
            <p>{author.bibliography}</p>
          </div>
        ))}
      </div>
    )
  }
  return <h2>Loading author...</h2>
}

export const authors = gql`
  query authors {
    authors {
      id
      name
      bibliography
      avatar {
        handle
      }
    }
  }
`

export default graphql(authors)(About)

// current/nuxt-apollo-blog/pages/about.vue
<template>
  <h2 v-if="loading > 0">
    Loading...
  </h2>
  <div v-else>
    <div v-for="author in authors" :key="author.id">
      <div class='author'>
        <div class='info-header'>
          <img
            :alt="author.name"
            :src="`https://media.graphcms.com/resize=w:100,h:100,fit:crop/${author.avatar.handle}`"
          />
          <h1>Hello! My name is {{author.name}}</h1>
        </div>
        <p>{{author.bibliography}}</p>
      </div>
    </div>
  </div>
</template>

<script>
  import gql from 'graphql-tag'

  export const authors = gql`
    query authors {
      authors {
        id
        name
        bibliography
        avatar {
          handle
        }
      }
    }
  `

  export default {
    name: 'AboutPage',
    data: () => ({
      loading: 0
    }),
    apollo: {
      $loadingKey: 'loading',
      authors: {
        query: authors
      }
    }
  }
</script>

<style scoped>
  .author {
    margin-bottom: 72px; 
  }
  .info-header {
    text-align: center;
  }
  img {
    height: 120px;
    width: auto;
  }
</style>
