// with-sveltekit-and-urql/src/routes/products/[slug].svelte
<script context="module">
  export const load = async ({ params }) => {
    const { slug } = params;
    return {
      props: { slug },
    };
  };
</script>

<script>
  export let slug;
  import { gql, operationStore, query } from '@urql/svelte';

  const productQuery = gql`
    query Product($slug: String!) {
      product(where: { slug: $slug }) {
        name
        description
        price
        image {
          url(transformation: { image: { resize: { fit: clip, height: 200 } } })
        }
        content {
          html
        }
      }
    }
  `;
  const product = operationStore(productQuery, { slug });

  query(product);
</script>

{#if $product.fetching}
  <p>Loading...</p>
{:else if $product.error}
  <p>Error! {$product.error.message}</p>
{:else}
  <div>
    <h1>{$product.data.product.name}</h1>
    <p>{$product.data.product.description}</p>
    <p>Price: €{$product.data.product.price / 100}</p>
    <img
      src={$product.data.product.image.url}
      alt={$product.data.product.name}
    />
    <div>
      {@html $product.data.product.content.html}
    </div>
  </div>
{/if}

// with-urql-react/pages/products/[slug].js
import { Fragment } from 'react';
import { useRouter } from 'next/router';
import { gql, useQuery } from 'urql';

export default function ProductPage() {
  const router = useRouter();

  const ProductBySlugQuery = gql`
    query GetProductBySlug($slug: String!) {
      product(where: { slug: $slug }) {
        name
        description
        price
      }
    }
  `;

  const [result] = useQuery({
    query: ProductBySlugQuery,
    variables: { slug: router.query.slug },
  });
  const { data, fetching, error } = result;

  if (fetching) return <p>Fetching product by slug</p>;
  if (error) return <p>Oh no... {error.message}</p>;

  return (
    <Fragment>
      <h1>{data.product.name}</h1>
      <p>{data.product.description}</p>
      <p>{data.product.price / 100}</p>
    </Fragment>
  );
}
