// react-urql-blog/src/components/Home.js
import React from 'react'
import { Link } from 'react-router-dom'
import { Connect, query } from 'urql'

const Home = () => (
  <Connect
    query={query(Posts)}
    children={({ loaded, data, error}) => {
      if (error) return <div>Error!</div>
      if (!loaded) return <div>Loading...</div>

      return (
      <section>
        <ul className='Home-ul'>
          {data.allPosts.map(post => (
            <li className='Home-li' key={`post-${post.id}`}>
              <Link to={`/post/${post.slug}`} className='Home-link'>
                <div className='Home-placeholder'>
                  <img
                    alt={post.title}
                    className='Home-img'
                    src={`https://media.graphcms.com/resize=w:100,h:100,fit:crop/${post.coverImage.handle}`}
                  />
                </div>
                <h3>{post.title}</h3>
              </Link>
            </li>
          ))}
        </ul>
      </section>
    )
    }
  } />
)

export const Posts = `{
  allPosts(orderBy: dateAndTime_DESC) {
    id
    slug
    title
    dateAndTime
    coverImage {
      handle
    }
  }
}`

export default Home

// with-vuejs/src/views/Home.vue
<template>
  <div class="home" id="products">
    <img alt="Vue logo" src="../assets/logo.png" />
    <router-link
      v-for="product in products"
      :to="{ name: 'Product', params: { slug: product.slug } }"
      :key="product.slug"
    >
      <article>
        <h1>{{ product.name }}</h1>
        <p>{{ product.description }}</p>
      </article>
    </router-link>
  </div>
</template>

<script>
// @ is an alias to /src
export default {
  name: 'Home',
  components: {},
  data() {
    return {
      products: [],
      loading: true,
      errors: [],
    };
  },
  async created() {
    const response = await fetch(
      'https://api-eu-central-1.graphcms.com/v2/ck8sn5tnf01gc01z89dbc7s0o/master',
      {
        method: 'POST',
        body: JSON.stringify({
          query: `{ products { name slug } }`,
        }),
      }
    );

    const { data } = await response.json();

    this.errors = data.errors;
    this.loading = false;
    this.products = data.products;
  },
};
</script>
